#Alex elkman
#999656002

All:
	g++ -Wall calculator.cpp Fraction.cpp Fraction.h -o homework1a
	g++ -Wall useFraction.cpp Fraction.cpp Fraction.h -o homework1b
calculator.o:
	g++ -c calculator.cpp
useFraction.o:
	g++ -c useFraction.cpp
